package Daje::Workflow::Client::Activity;
use Mojo::Base 'Daje::Workflow::Common::Activity::Base', -base, -signatures;
use v5.40;


# NAME
# ====
#
# Daje::Client::Activity - Create a client
#
# SYNOPSIS
# ========
#
#     use Daje::Client::Activity;
#
# DESCRIPTION
# ===========
#
# Daje::Client::Activity is ...
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.comE<gt>
#

use Daje::Database::Model::Users;
use Daje::Database::Model::Companies;
use Daje::Workflow::Database::Model::Workflow;

our $VERSION = "0.01";

sub create_client($self) {
    try {
        $self->model->insert_history("New client will be created", "Daje::Workflow::Client::Activity");
        my $wfl = Daje::Workflow::Database::Model::Workflow->new(db $self->db);
        $self->add_user($wfl);
        $self->add_company($wfl);
        $self->model->insert_history("New client created", "Daje::Workflow::Client::Activity");
    } catch ($e) {
        $self->error->add_error("Adding client failed due to : '$e'");
    };

}

sub add_company($self, $wfl) {
    my $company = $self->context->{context}->{company};
    my $workflow->{name} = "companies";
    $workflow->{state} = "company_active";

    my $workflow_pkey = $wfl->save($workflow);
    $company->{workflow_fkey} = $workflow_pkey;

    my $company_obj->Daje::Database::Model::Companies->new(
        db => $self->db
    );
    $company_obj->insert_companies($company);
}

sub add_user($self, $wfl) {
    my $user = $self->context()->{context}->{user};

    my $workflow->{name} = "users";
    $workflow->{state} = "user_active";

    my $workflow_pkey = $wfl->save($workflow);
    $user->{workflow_fkey} = $workflow_pkey;

    my $user_obj = Daje::Database::Model::Users->new(
        db => $self->db
    );
    $user_obj->insert_users($user);

}

1;
__END__




#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Client::Activity - Create a client



=head1 SYNOPSIS


    use Daje::Client::Activity;



=head1 DESCRIPTION


Daje::Client::Activity is ...



=head1 REQUIRES

L<Daje::Client::Create> 

L<v5.40> 

L<Mojo::Base> 


=head1 METHODS

=head2 create_client($self)

 create_client($self)();


=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.comE<gt>



=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

