package Daje::Workflow::Client::Activity;
use Mojo::Base 'Daje::Workflow::Common::Activity::Base', -base, -signatures;
use v5.40;


# NAME
# ====
#
# Daje::Workflow::Client::Activity - Create a client
#
# SYNOPSIS
# ========
#
#     use Daje::Workflow::Client::Activity;
#
# DESCRIPTION
# ===========
#
# Daje::Workflow::Client::Activity is ...
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.comE<gt>
#


our $VERSION = "0.01";

sub create_client($self) {


}

1;
__END__



#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Client::Create - It's new $module



=head1 SYNOPSIS


    use Daje::Client::Create;



=head1 DESCRIPTION


Daje::Client::Create is ...



=head1 REQUIRES

L<v5.40> 

L<Mojo::Base> 


=head1 METHODS


=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.comE<gt>



=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

